Repository tepachelabs/perro-cafe-storefront, pull requests merged in 2023-05, with the labels that each got.

#50 SHO-83: Issue, page has two header elements
  app/components/organisms/navbar/navbar.component.tsx
  app/components/organisms/navbar/navbar.styles.tsx
Labels: 👍 Approved

#51 SHO-79: RegularsInfo Template
  app/components/atoms/divider/index.ts
  app/components/atoms/numeral/img/numeral-bg.svg
  app/components/atoms/numeral/index.ts
  app/components/atoms/numeral/numeral.component.tsx
  app/components/atoms/numeral/numeral.stories.tsx
  app/components/atoms/numeral/numeral.styles.tsx
  app/components/molecules/subtitle/subtitle.component.tsx
  app/components/molecules/subtitle/subtitle.stories.tsx
  app/components/molecules/subtitle/subtitle.styles.tsx
  app/components/templates/regulars-info/index.ts
  app/components/templates/regulars-info/regulars-info.component.tsx
  app/components/templates/regulars-info/regulars-info.stories.tsx
  app/components/templates/regulars-info/regulars-info.styles.tsx
  app/config.json
  app/routes/frecuentes.tsx
  app/theme.ts
Labels: ✋Ready for review

#52 SHO-81: Menu page
  app/components/templates/menu-page/index.ts
  app/components/templates/menu-page/menu-page.component.tsx
  app/components/templates/menu-page/menu-page.stories.tsx
  app/components/templates/menu-page/menu-page.styles.tsx
  app/config.json
  app/routes/menu.tsx
  app/utils.ts
Labels: ✋Ready for review

#53 Styles migration: Removing styled-components in favor of @emotion/styled
  .storybook/preview.js
  @types/emotion.d.ts
  app/components/atoms/arrow-button/arrow-button.styles.tsx
  app/components/atoms/badge/badge.styles.tsx
  app/components/atoms/carousel-circle/carousel-circle.component.tsx
  app/components/atoms/divider/divider.styles.tsx
  app/components/atoms/explosion-badge/explosion-badge.styles.tsx
  app/components/atoms/horizontal-button/horizontal-button.styles.tsx
  app/components/atoms/hr/hr.component.tsx
  app/components/atoms/icon/icon.component.tsx
  app/components/atoms/map-sketch/map-sketch.styles.tsx
  app/components/atoms/numeral/numeral.styles.tsx
  app/components/atoms/paragraph/paragraph.component.tsx
  app/components/atoms/review-card/review-card.styles.tsx
  app/components/atoms/see-menu-button/see-menu-button.styles.tsx
  app/components/molecules/perk-info/perk-info.styles.tsx
  app/components/molecules/promotion-card/promotion-card.styles.tsx
  app/components/molecules/social-media-buttons/social-media-button.styles.tsx
  app/components/molecules/subtitle/subtitle.styles.tsx
  app/components/organisms/carousel/carousel.styles.tsx
  app/components/organisms/hero/hero.styles.tsx
  app/components/organisms/navbar/navbar.styles.tsx
  app/components/organisms/regulars-hero/regulars-hero.styles.tsx
  app/components/templates/community/community.styles.tsx
  app/components/templates/cult/cult.stories.tsx
  app/components/templates/cult/cult.styles.tsx
  app/components/templates/footer/footer.styles.tsx
  app/components/templates/landing-skeleton/landing-skeleton.styles.tsx
  app/components/templates/menu-page/menu-page.styles.tsx
  app/components/templates/menu/menu.styles.tsx
  app/components/templates/regulars-info/regulars-info.styles.tsx
  app/components/templates/temple/temple.styles.tsx
  app/entry.server.tsx
  app/global.styles.tsx
  app/root.tsx
  app/theme.ts
  app/utils.ts
  package-lock.json
  package.json
  remix.config.js
  tsconfig.json
Labels: ⌛In Progress
